"""FABLE Table Engine — AI-facilitated tabletop RPG table engine.

The package exposes deterministic rules/state machinery, access-controlled
event projection, model-call routing, persistence, and text-session interfaces.
"""

from .auditor import AuditFlag, AuditResult, AuditTier, Auditor
from .beat import ActionLifecycleState, BeatResult, BeatRunner, DeliveryScope
from .console import PlaytestSession, epistemic_label, parse_proposal, render_event
from .plot_graph import (
    Faction,
    FixtureBinding,
    Front,
    FunctionNode,
    Hook,
    InterestSignal,
    InterestSignalAccumulator,
    PlotGraph,
)
from .plot_manager import FixtureIssue, PlotManager
from .orchestrator import ActionQueue, Orchestrator, SceneCadence, SceneMode, TurnGrant, TurnMode
from .character_agent import CharacterAgent, Proposal
from .character_sheet import BondRef, CharacterSheet
from .persona import PersonaSpec
from .access import (
    OVERRIDE_TYPE,
    CanonConflictError,
    CommitPipeline,
    Conflict,
    Fact,
    canon_ledger,
    committed_facts,
)
from .context import Belief, BeliefStore, ContextAssembler
from .effects import (
    AdvanceClock,
    ApplyScar,
    ApplyStress,
    ChangeAccess,
    ChangeResource,
    ChangeTruth,
    CreateMaintainedTruth,
    CreateTruth,
    EDGE_CAP,
    EFFECT_AUTHOR,
    EFFECT_EVENT_TYPE,
    EffectExecutor,
    EffectResult,
    ExpireMaintainedTruth,
    ExpireTruth,
    GainEdge,
    MoveEntity,
    SCAR_CAP,
    SpendEdge,
    STRESS_CAP,
    TypedEffect,
    describe_effect,
    effect_from_dict,
)
from .gm import AdjudicatorGM, NarratorGM, ResolutionPlan, StakesDecision, WorldSimulator
from .budgeter import (
    BudgetCheckResult,
    ContextBudgetPolicy,
    ContextBudgeter,
    TokenEstimator,
)
from .lorebook import LoreAssembler, LoreDeck, LoreEntry
from .provider import (
    AnthropicAdapter,
    CallRecord,
    CostCeilingStatus,
    ModelCallError,
    ModelGateway,
    ProviderAdapter,
    TelemetrySink,
    ToolOutputError,
)
from .social import (
    COMPEL_AUTHOR,
    CompelResolution,
    PendingCompel,
    SocialInterpreter,
    resolve_compel,
)
from .dice import DiceResult, DiceService
from .event_log import EventLog
from .events import (
    CHANNELS,
    CORRECTION_TYPES,
    EPISTEMIC_TYPES,
    MECHANICAL_TYPES,
    ROLL_VISIBILITY_LEVELS,
    TRANSFER_TYPES,
    VISIBILITY_LEVELS,
    Commitment,
    DeterminismBoundaryError,
    Event,
    ProjectedEvent,
)
from .perception import (
    MAY_HAVE_PERCEIVED,
    PERCEPTION_AUTHOR,
    Scene,
    Stimulus,
    derive_overhears,
    perceivers,
    perception_map,
    perceptible_entities,
)
from .campaign import CampaignPackage, load_campaign, load_campaign_dict
from .disposition import (
    DispositionAxis,
    DispositionDelta,
    DispositionEngine,
    DispositionGraph,
)
from .persistence import (
    ENGINE_SCHEMA_VERSION,
    SchemaVersionError,
    SessionManifest,
    SessionManager,
    SQLiteDispositionGraph,
    SQLiteEventLog,
    SQLitePlotGraph,
    SQLiteScene,
    SQLiteWorldState,
    attach_campaign,
    attach_disposition,
    open_session,
)
from .interface import HomeScreen, PlayInterface, build_play_interface
from .rules import Band, CheckResult, RulesEngine, band_for_margin
from .settings import SettingsManager, SettingsRegistry, load_settings, reset_setting
from .world_state import ELAPSED_CATEGORIES, Entity, WorldState

__version__ = "0.1.0"

__all__ = [
    "ActionLifecycleState",
    "ActionQueue",
    "AdvanceClock",
    "AdjudicatorGM",
    "ApplyScar",
    "ApplyStress",
    "AuditFlag",
    "AuditResult",
    "AuditTier",
    "Auditor",
    "Band",
    "BeatResult",
    "BondRef",
    "BeatRunner",
    "DeliveryScope",
    "Belief",
    "PlaytestSession",
    "BeliefStore",
    "CharacterAgent",
    "CharacterSheet",
    "CHANNELS",
    "CORRECTION_TYPES",
    "EPISTEMIC_TYPES",
    "TRANSFER_TYPES",
    "CanonConflictError",
    "ChangeAccess",
    "ChangeResource",
    "ChangeTruth",
    "CheckResult",
    "CommitPipeline",
    "Commitment",
    "Conflict",
    "ContextAssembler",
    "CreateMaintainedTruth",
    "CreateTruth",
    "DeterminismBoundaryError",
    "DiceResult",
    "DiceService",
    "DispositionAxis",
    "DispositionDelta",
    "DispositionEngine",
    "DispositionGraph",
    "SQLiteDispositionGraph",
    "attach_disposition",
    "COMPEL_AUTHOR",
    "CompelResolution",
    "describe_effect",
    "effect_from_dict",
    "EDGE_CAP",
    "SCAR_CAP",
    "STRESS_CAP",
    "EFFECT_AUTHOR",
    "EFFECT_EVENT_TYPE",
    "EffectExecutor",
    "EffectResult",
    "GainEdge",
    "SpendEdge",
    "Entity",
    "ExpireMaintainedTruth",
    "ExpireTruth",
    "Event",
    "EventLog",
    "Faction",
    "Fact",
    "FixtureBinding",
    "FixtureIssue",
    "Front",
    "FunctionNode",
    "Hook",
    "InterestSignal",
    "InterestSignalAccumulator",
    "MAY_HAVE_PERCEIVED",
    "ModelCallError",
    "ModelGateway",
    "MoveEntity",
    "NarratorGM",
    "PendingCompel",
    "PersonaSpec",
    "ResolutionPlan",
    "PlotGraph",
    "PlotManager",
    "Proposal",
    "MECHANICAL_TYPES",
    "ROLL_VISIBILITY_LEVELS",
    "OVERRIDE_TYPE",
    "PERCEPTION_AUTHOR",
    "ProjectedEvent",
    "HomeScreen",
    "PlayInterface",
    "build_play_interface",
    "RulesEngine",
    "SettingsManager",
    "SettingsRegistry",
    "load_settings",
    "reset_setting",
    "CampaignPackage",
    "SQLiteEventLog",
    "SQLitePlotGraph",
    "TypedEffect",
    "SQLiteScene",
    "SQLiteWorldState",
    "attach_campaign",
    "load_campaign",
    "load_campaign_dict",
    "Scene",
    "SceneCadence",
    "SceneMode",
    "StakesDecision",
    "Stimulus",
    "VISIBILITY_LEVELS",
    "ELAPSED_CATEGORIES",
    "WorldState",
    "AnthropicAdapter",
    "BudgetCheckResult",
    "CallRecord",
    "ContextBudgetPolicy",
    "ContextBudgeter",
    "CostCeilingStatus",
    "LoreAssembler",
    "LoreDeck",
    "LoreEntry",
    "ProviderAdapter",
    "TelemetrySink",
    "TokenEstimator",
    "ToolOutputError",
    "epistemic_label",
    "parse_proposal",
    "render_event",
    "band_for_margin",
    "canon_ledger",
    "committed_facts",
    "derive_overhears",
    "WorldSimulator",
    "SocialInterpreter",
    "resolve_compel",
    "open_session",
    "Orchestrator",
    "perceivers",
    "perception_map",
    "perceptible_entities",
    "TurnGrant",
    "TurnMode",
    "ENGINE_SCHEMA_VERSION",
    "SchemaVersionError",
    "SessionManifest",
    "SessionManager",
    "__version__",
]
